services:
  date:
    image: vitalyvitmens/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: vitalyvitmens/result
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - date
